# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'jabMix1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    pod 'SKPhotoBrowser'
  use_frameworks!

  # Pods for jabMix1

pod 'Firebase/Core'

pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Messaging'
pod 'SVProgressHUD'
pod 'KMPlaceholderTextView', '~> 1.3.0'
pod 'GooglePlaces'
pod 'GooglePlacePicker'
pod 'GoogleMaps'
pod 'GooglePlacesSearchController'
pod 'JSQMessagesViewController'
pod 'MessageKit'
pod 'UIColor_Hex_Swift', '~> 4.0.1'
pod 'TwitterKit'
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'
pod 'RealmSwift'


end
